import React, { useState } from 'react'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import ChallengeModel from './components/ChallengeModel'
import Beneficiaries from './components/Beneficiaries'
import ContactForm from './components/ContactForm'
import Footer from './components/Footer'

const translations = {
  en: {
    logo: 'Kedalup Energy',
    home: 'Home',
    about: 'About',
    services: 'Services',
    contact: 'Contact',
    bookPickup: 'Book a Pickup',
    languageLabel: 'Language',
    heroTitle: 'Powering Schools.\nEmpowering Communities.',
    heroSubtitle: 'Creating sustainable futures through renewable energy partnerships with Aboriginal communities, schools, and charities.',
    seeHowItWorks: 'See How It Works',
    getInvolved: 'Get Involved',
    contactHeading: 'Ready to Make a Difference?',
    fullNameLabel: 'Full Name',
    emailLabel: 'Email Address',
    phoneLabel: 'Telephone Number',
    organizationLabel: 'Organization',
    positionLabel: 'Job Position',
    namePlaceholder: 'Enter your full name',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'e.g. (08) 9321 0000',
    organizationPlaceholder: 'Enter organization or school name',
    positionPlaceholder: 'Enter your job position',
    submitButton: 'Send Message',
    successTitle: 'Enquiry Sent Successfully!',
    successMessage: 'Thank you for reaching out to Kedalup Energy. Our community solar team will contact you shortly.',
    sendAnother: 'Send Another Message'
    ,
    challengeHeading: 'The Challenge',
    challengeText: 'Schools and communities face increasing energy costs and environmental challenges. Traditional funding models limit their ability to invest in sustainable solutions that could benefit future generations.',
    challengeImageAlt: 'Rooftop solar panel array reflecting sunset',
    modelTitle: 'The Kedalup Model',
    freeInstallation: 'Free Installation',
    freeInstallationDesc: 'We install solar and EV stations at schools at zero cost',
    discountedEnergy: 'Discounted Energy',
    discountedEnergyDesc: 'Provide reduced rates through power purchase agreements',
    fullMaintenance: 'Full Maintenance',
    fullMaintenanceDesc: 'Ongoing system maintenance and support included',
    profitSharing: 'Profit Sharing',
    profitSharingDesc: '50% of profits reinvested into schools and charities',
    beneficiariesHeading: 'Who Benefits',
    beneficiaries: [
      { title: 'Schools', description: 'Reduced energy bills and learning opportunities.' },
      { title: 'Councils', description: 'Supporting local community goals.' },
      { title: 'Charities', description: 'Funding for critical community programs.' },
      { title: 'Government', description: 'Meeting renewable energy targets.' },
      { title: 'Communities', description: 'Cleaner environment and local jobs.' }
    ],
    footerDescription: 'Powering Australian schools and communities through community solar.',
    quickLinksTitle: 'Quick Links',
    contactsTitle: 'Contacts',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'Perth, Western Australia',
    copyright: 'All rights reserved.',
    privacy: 'Privacy Policy',
    terms: 'Terms of Service'
    ,
    requiredName: 'Full name is required.',
    requiredOrganization: 'Organization name is required.',
    requiredPosition: 'Job position is required.',
    requiredEmail: 'Email address is required.',
    invalidEmail: 'Please enter a valid email address.',
    requiredPhone: 'Telephone number is required.',
    invalidPhone: 'Please enter a valid telephone number (8-15 digits).',
    submitting: 'Submitting...'
  },
  si: {
    logo: 'Kedalup Energy',
    home: 'මුල් පිටුව',
    about: 'අප ගැන',
    services: 'සේවාවන්',
    contact: 'සම්බන්ධ වන්න',
    bookPickup: 'ඇණවුමක් කරන්න',
    languageLabel: 'භාෂාව',
    heroTitle: 'පාසල් බලය සපයයි.\nප්‍රජාවන්ට ශක්තිය දෙයි.',
    heroSubtitle: 'ඇබොරීයජින් ප්‍රජාවන්, පාසැල් සහ චාරිටී සමඟ නවීන බලශක්ති සහයෝගීතාවයන් ඔස්සේ ස්ථාවර අනාගතයක් නිර්මාණය කිරීම.',
    seeHowItWorks: 'කෙසේ ක්‍රියා කරන්නේද බලන්න',
    getInvolved: 'එකට වන්න',
    contactHeading: 'වෙනසක් කිරීමට සූදානම්ද?',
    fullNameLabel: 'සම්පූර්ණ නම',
    emailLabel: 'ඊමේල් ලිපිනය',
    phoneLabel: 'දුරකථන අංකය',
    organizationLabel: 'සංවිධානය',
    positionLabel: 'තනතුර',
    namePlaceholder: 'ඔබගේ සම්පූර්ණ නම ඇතුළත් කරන්න',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'උදා: (08) 9321 0000',
    organizationPlaceholder: 'සංවිධානය හෝ පාසල ඇතුළත් කරන්න',
    positionPlaceholder: 'ඔබගේ තනතුර ඇතුළත් කරන්න',
    submitButton: 'යවන්න',
    successTitle: 'අයදුම සාර්ථකව යවා ඇත!',
    successMessage: 'Kedalup Energy වෙත සම්බන්ධ වීම සඳහා ස්තුතියි. අපගේ සූර්ය කණ්ඩායම ඔබව ඉක්මනින් සම්බන්ධ කරනු ඇත.',
    sendAnother: 'තවත් පණිවිඩයක් යවන්න'
    ,
    challengeHeading: 'අභියෝගය',
    challengeText: 'පාසල් සහ ප්‍රජාවන්ට ඉහල බලශක්ති වියදම් සහ පරිසරමය අභියෝගයක් මතු වේ. පැරණි මුදල් ආකෘති ස්ථාවර විසඳුම් සඳහා ආයෝජනය කිරීමට සීමා වනවා.',
    challengeImageAlt: 'උදෑසන දැකුම්කළු කිරණ සමඟ වහලය මත සූර්ය පැනල්',
    modelTitle: 'Kedalup ආකෘතිය',
    freeInstallation: 'නිදහස් ස්ථාපනය',
    freeInstallationDesc: 'පාසලවලට සූර්ය සහ EV ස්ථාන ශුන්‍ය පිරිවැයෙන් ස්ථාපනය කරයි',
    discountedEnergy: 'වැඩි වට්ටම් සහිත බලශක්ති',
    discountedEnergyDesc: 'බල මිල ගණන් ගනුදෙනු හරහා අඩු මිලක් ලබාදෙයි',
    fullMaintenance: 'සම්පුර්ණ නඩත්තු කිරීම',
    fullMaintenanceDesc: 'විධානය නඩත්තු කිරීම සහ සහාය ඇතුළත්යි',
    profitSharing: 'ලාභ බෙදා ගැනීම',
    profitSharingDesc: 'ලාභ 50% පාසල් සහ චාරිටීන් වෙත ප්නව්‍ය',
    beneficiariesHeading: 'හිතකරයන්',
    beneficiaries: [
      { title: 'පාසල්', description: 'බලශක්ති බිල්පත් අඩුවීම හා ඉගෙනුම් අවස්ථා.' },
      { title: 'මහා නගර සභා', description: 'දේශීය ප්‍රජා ඉලක්ක සහාය.' },
      { title: 'චාරිටී', description: 'ප්‍රජාව සඳහා වැදගත් වැඩසටහන් සඳහා අරමුදල්.' },
      { title: 'රජය', description: 'නවීන බලශක්ති ඉලක්ක සපුරාලීම.' },
      { title: 'ප්‍රජාවන්', description: 'පිරිසිදු පරිසරය සහ දේශීය රැකියා.' }
    ],
    footerDescription: 'ප්‍රජා සූර්ය බලශක්තිය ඔස්සේ ඕස්ටේලියානු පාසල් සහ ප්‍රජාවන්ට බලය සැපයීම.',
    quickLinksTitle: 'ඉක්මන් සබැඳි',
    contactsTitle: 'සම්බන්ධතා',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'පර්ත්, බටහිර ඕස්ට්‍රේලියාව',
    copyright: 'සියලුම හිමිකම් ඇවිරිණි.',
    privacy: 'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',
    terms: 'සේවා කොන්දේසි'
    ,
    requiredName: 'සම්පූර්ණ නම අවශ්‍යයි.',
    requiredOrganization: 'සංවිධානයේ නාමය අවශ්‍යයි.',
    requiredPosition: 'තනතුර අවශ්‍යයි.',
    requiredEmail: 'ඊමේල් ලිපිනය අවශ්‍යයි.',
    invalidEmail: 'කරුණාකර සත්‍ය ඊමේල් ලිපිනයක් ඇතුළත් කරන්න.',
    requiredPhone: 'දුරකථන අංකය අවශ්‍යයි.',
    invalidPhone: 'කරුණාකර වලංගු දුරකථන අංකයක් ඇතුළත් කරන්න (8-15 අංක).',
    submitting: 'යවමින්...' 
  },
  ar: {
    logo: 'Kedalup Energy',
    home: 'الصفحة الرئيسية',
    about: 'حول',
    services: 'الخدمات',
    contact: 'اتصل',
    bookPickup: 'احجز التوصيل',
    languageLabel: 'اللغة',
    heroTitle: 'تمكين المدارس.\nتمكين المجتمعات.',
    heroSubtitle: 'نبني مستقبلًا مستدامًا من خلال شراكات الطاقة المتجددة مع المجتمعات، والمدارس، والجمعيات الخيرية.',
    seeHowItWorks: 'أعرف كيف يعمل',
    getInvolved: 'انضم الآن',
    contactHeading: 'هل أنت مستعد لإحداث فرق؟',
    fullNameLabel: 'الاسم الكامل',
    emailLabel: 'البريد الإلكتروني',
    phoneLabel: 'رقم الهاتف',
    organizationLabel: 'المنظمة',
    positionLabel: 'المنصب',
    namePlaceholder: 'أدخل اسمك الكامل',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'مثال: (08) 9321 0000',
    organizationPlaceholder: 'أدخل اسم المنظمة أو المدرسة',
    positionPlaceholder: 'أدخل منصبك',
    submitButton: 'إرسال',
    successTitle: 'تم إرسال الاستفسار بنجاح!',
    successMessage: 'شكرًا لتواصلك مع Kedalup Energy. سيتواصل فريقنا قريبًا.',
    sendAnother: 'أرسل رسالة أخرى'
    ,
    challengeHeading: 'التحدي',
    challengeText: 'تواجه المدارس والمجتمعات ارتفاع تكاليف الطاقة وتحديات بيئية. تقيد نماذج التمويل التقليدية قدرتها على الاستثمار في حلول مستدامة.',
    challengeImageAlt: 'مصفوفة ألواح شمسية على السطح تعكس الغروب',
    modelTitle: 'نموذج Kedalup',
    freeInstallation: 'تركيب مجاني',
    freeInstallationDesc: 'نركب أنظمة شمسية ومحطات EV في المدارس دون تكلفة',
    discountedEnergy: 'طاقة مخفضة',
    discountedEnergyDesc: 'توفير أسعار مخفضة عبر اتفاقيات شراء الطاقة',
    fullMaintenance: 'صيانة كاملة',
    fullMaintenanceDesc: 'صيانة النظام المستمرة والدعم متضمن',
    profitSharing: 'تقاسم الأرباح',
    profitSharingDesc: 'إعادة استثمار 50% من الأرباح في المدارس والجمعيات الخيرية',
    beneficiariesHeading: 'المستفيدون',
    beneficiaries: [
      { title: 'المدارس', description: 'تقليل فواتير الطاقة وفرص تعليمية.' },
      { title: 'الجهات المحلية', description: 'دعم أهداف المجتمع المحلي.' },
      { title: 'الجمعيات الخيرية', description: 'تمويل برامج مجتمعية مهمة.' },
      { title: 'الحكومة', description: 'تحقيق أهداف الطاقة المتجددة.' },
      { title: 'المجتمعات', description: 'بيئة أنظف ووظائف محلية.' }
    ],
    footerDescription: 'تمكين المدارس والمجتمعات الأسترالية من خلال الطاقة الشمسية المجتمعية.',
    quickLinksTitle: 'روابط سريعة',
    contactsTitle: 'جهات الاتصال',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'بيرث، أستراليا الغربية',
    copyright: 'جميع الحقوق محفوظة.',
    privacy: 'سياسة الخصوصية',
    terms: 'شروط الخدمة'
    ,
    requiredName: 'الاسم الكامل مطلوب.',
    requiredOrganization: 'اسم المؤسسة مطلوب.',
    requiredPosition: 'المسمى الوظيفي مطلوب.',
    requiredEmail: 'البريد الإلكتروني مطلوب.',
    invalidEmail: 'الرجاء إدخال عنوان بريد إلكتروني صالح.',
    requiredPhone: 'رقم الهاتف مطلوب.',
    invalidPhone: 'الرجاء إدخال رقم هاتف صالح (8-15 أرقام).',
    submitting: 'جارٍ الإرسال...'
  },
  fr: {
    logo: 'Kedalup Energy',
    home: 'Accueil',
    about: 'À propos',
    services: 'Services',
    contact: 'Contact',
    bookPickup: 'Réserver une collecte',
    languageLabel: 'Langue',
    heroTitle: 'Alimenter les écoles.\nAutonomiser les communautés.',
    heroSubtitle: 'Créer des avenirs durables grâce à des partenariats en énergie renouvelable avec des communautés autochtones, des écoles et des associations caritatives.',
    seeHowItWorks: 'Voir comment ça marche',
    getInvolved: 'Participer',
    contactHeading: 'Prêt à faire la différence ?',
    fullNameLabel: 'Nom complet',
    emailLabel: 'Adresse e-mail',
    phoneLabel: 'Numéro de téléphone',
    organizationLabel: 'Organisation',
    positionLabel: 'Poste',
    namePlaceholder: 'Entrez votre nom complet',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'ex : (08) 9321 0000',
    organizationPlaceholder: 'Entrez le nom de l’organisation ou de l’école',
    positionPlaceholder: 'Entrez votre poste',
    submitButton: 'Envoyer',
    successTitle: 'Demande envoyée avec succès !',
    successMessage: 'Merci de contacter Kedalup Energy. Notre équipe solaire vous contactera bientôt.',
    sendAnother: 'Envoyer un autre message'
    ,
    challengeHeading: 'Le défi',
    challengeText: 'Les écoles et les communautés font face à une hausse des coûts énergétiques et à des défis environnementaux. Les modèles de financement traditionnels limitent leur capacité à investir dans des solutions durables.',
    challengeImageAlt: 'Panneaux solaires sur le toit reflétant le coucher du soleil',
    modelTitle: 'Le modèle Kedalup',
    freeInstallation: 'Installation gratuite',
    freeInstallationDesc: 'Nous installons des stations solaires et EV dans les écoles sans coût',
    discountedEnergy: 'Énergie à prix réduit',
    discountedEnergyDesc: 'Tarifs réduits via des accords d’achat d’électricité',
    fullMaintenance: 'Maintenance complète',
    fullMaintenanceDesc: 'Maintenance continue du système et support inclus',
    profitSharing: 'Partage des bénéfices',
    profitSharingDesc: '50% des bénéfices réinvestis dans les écoles et les associations',
    beneficiariesHeading: 'Bénéficiaires',
    beneficiaries: [
      { title: 'Écoles', description: 'Factures d’énergie réduites et opportunités d’apprentissage.' },
      { title: 'Collectivités', description: 'Soutien aux objectifs communautaires locaux.' },
      { title: 'Associations caritatives', description: 'Financement de programmes communautaires essentiels.' },
      { title: 'Gouvernement', description: 'Atteindre les objectifs d’énergie renouvelable.' },
      { title: 'Communautés', description: 'Environnement plus propre et emplois locaux.' }
    ],
    footerDescription: 'Alimenter les écoles et communautés australiennes grâce au solaire communautaire.',
    quickLinksTitle: 'Liens rapides',
    contactsTitle: 'Contacts',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'Perth, Australie-Occidentale',
    copyright: 'Tous droits réservés.',
    privacy: 'Politique de confidentialité',
    terms: 'Conditions d’utilisation'
    ,
    requiredName: 'Le nom complet est requis.',
    requiredOrganization: 'Le nom de l’organisation est requis.',
    requiredPosition: 'Le poste est requis.',
    requiredEmail: 'L’adresse e-mail est requise.',
    invalidEmail: 'Veuillez entrer une adresse e-mail valide.',
    requiredPhone: 'Le numéro de téléphone est requis.',
    invalidPhone: 'Veuillez entrer un numéro de téléphone valide (8-15 chiffres).',
    submitting: 'Envoi...'
  },
  de: {
    logo: 'Kedalup Energy',
    home: 'Startseite',
    about: 'Über',
    services: 'Dienstleistungen',
    contact: 'Kontakt',
    bookPickup: 'Abholung buchen',
    languageLabel: 'Sprache',
    heroTitle: 'Schulen mit Energie versorgen.\nGemeinschaften stärken.',
    heroSubtitle: 'Nachhaltige Zukunft durch erneuerbare Energiepartnerschaften mit indigenen Gemeinschaften, Schulen und Wohltätigkeitsorganisationen schaffen.',
    seeHowItWorks: 'So funktioniert es',
    getInvolved: 'Mitmachen',
    contactHeading: 'Bereit, etwas zu bewirken?',
    fullNameLabel: 'Vollständiger Name',
    emailLabel: 'E-Mail-Adresse',
    phoneLabel: 'Telefonnummer',
    organizationLabel: 'Organisation',
    positionLabel: 'Position',
    namePlaceholder: 'Geben Sie Ihren vollständigen Namen ein',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'z. B. (08) 9321 0000',
    organizationPlaceholder: 'Geben Sie den Namen der Organisation oder Schule ein',
    positionPlaceholder: 'Geben Sie Ihre Position ein',
    submitButton: 'Senden',
    successTitle: 'Anfrage erfolgreich gesendet!',
    successMessage: 'Danke, dass Sie Kedalup Energy kontaktiert haben. Unser Solarteams meldet sich bald.',
    sendAnother: 'Noch eine Nachricht senden'
    ,
    challengeHeading: 'Die Herausforderung',
    challengeText: 'Schulen und Gemeinden stehen vor steigenden Energiekosten und Umweltproblemen. Traditionelle Finanzierungsmodelle schränken ihre Fähigkeit ein, in nachhaltige Lösungen zu investieren.',
    challengeImageAlt: 'Solarmodule auf dem Dach, die den Sonnenuntergang reflektieren',
    modelTitle: 'Das Kedalup-Modell',
    freeInstallation: 'Kostenlose Installation',
    freeInstallationDesc: 'Wir installieren Solar- und EV-Stationen an Schulen kostenlos',
    discountedEnergy: 'Vergünstigte Energie',
    discountedEnergyDesc: 'Günstigere Tarife durch Stromkaufverträge',
    fullMaintenance: 'Vollständige Wartung',
    fullMaintenanceDesc: 'Laufende Systemwartung und Unterstützung inbegriffen',
    profitSharing: 'Gewinnbeteiligung',
    profitSharingDesc: '50% der Gewinne werden in Schulen und Wohltätigkeitsorganisationen reinvestiert',
    beneficiariesHeading: 'Wer profitiert',
    beneficiaries: [
      { title: 'Schulen', description: 'Reduzierte Energierechnungen und Lernmöglichkeiten.' },
      { title: 'Kommunen', description: 'Unterstützung lokaler Gemeinschaftsziele.' },
      { title: 'Wohltätigkeiten', description: 'Finanzierung wichtiger Gemeinschaftsprogramme.' },
      { title: 'Regierung', description: 'Erreichen von Zielen für erneuerbare Energien.' },
      { title: 'Gemeinschaften', description: 'Sauberere Umwelt und lokale Arbeitsplätze.' }
    ],
    footerDescription: 'Stromversorgung australischer Schulen und Gemeinden durch gemeinschaftliche Solarenergie.',
    quickLinksTitle: 'Schnellzugriffe',
    contactsTitle: 'Kontakte',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'Perth, Western Australia',
    copyright: 'Alle Rechte vorbehalten.',
    privacy: 'Datenschutzrichtlinie',
    terms: 'Nutzungsbedingungen'
    ,
    requiredName: 'Vollständiger Name ist erforderlich.',
    requiredOrganization: 'Name der Organisation ist erforderlich.',
    requiredPosition: 'Stellenbezeichnung ist erforderlich.',
    requiredEmail: 'E-Mail-Adresse ist erforderlich.',
    invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    requiredPhone: 'Telefonnummer ist erforderlich.',
    invalidPhone: 'Bitte geben Sie eine gültige Telefonnummer ein (8-15 Stellen).',
    submitting: 'Wird gesendet...'
  },
  es: {
    logo: 'Kedalup Energy',
    home: 'Inicio',
    about: 'Acerca de',
    services: 'Servicios',
    contact: 'Contacto',
    bookPickup: 'Reservar recogida',
    languageLabel: 'Idioma',
    heroTitle: 'Impulsando escuelas.\nEmpoderando comunidades.',
    heroSubtitle: 'Creando futuros sostenibles a través de asociaciones de energía renovable con comunidades indígenas, escuelas y organizaciones benéficas.',
    seeHowItWorks: 'Ver cómo funciona',
    getInvolved: 'Participar',
    contactHeading: '¿Listo para hacer una diferencia?',
    fullNameLabel: 'Nombre completo',
    emailLabel: 'Correo electrónico',
    phoneLabel: 'Número de teléfono',
    organizationLabel: 'Organización',
    positionLabel: 'Puesto',
    namePlaceholder: 'Ingrese su nombre completo',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: 'Ej: (08) 9321 0000',
    organizationPlaceholder: 'Ingrese el nombre de la organización o escuela',
    positionPlaceholder: 'Ingrese su puesto',
    submitButton: 'Enviar',
    successTitle: '¡Consulta enviada con éxito!',
    successMessage: 'Gracias por contactar a Kedalup Energy. Nuestro equipo solar se pondrá en contacto pronto.',
    sendAnother: 'Enviar otro mensaje'
    ,
    challengeHeading: 'El desafío',
    challengeText: 'Las escuelas y las comunidades enfrentan crecientes costos de energía y desafíos ambientales. Los modelos de financiación tradicionales limitan su capacidad para invertir en soluciones sostenibles.',
    challengeImageAlt: 'Matriz de paneles solares en el techo reflejando la puesta de sol',
    modelTitle: 'El modelo Kedalup',
    freeInstallation: 'Instalación gratuita',
    freeInstallationDesc: 'Instalamos estaciones solares y EV en escuelas sin costo',
    discountedEnergy: 'Energía con descuento',
    discountedEnergyDesc: 'Tarifas reducidas a través de acuerdos de compra de energía',
    fullMaintenance: 'Mantenimiento completo',
    fullMaintenanceDesc: 'Mantenimiento continuo del sistema y soporte incluido',
    profitSharing: 'Participación de beneficios',
    profitSharingDesc: '50% de las ganancias reinvertidas en escuelas y organizaciones benéficas',
    beneficiariesHeading: 'Quién se beneficia',
    beneficiaries: [
      { title: 'Escuelas', description: 'Facturas de energía reducidas y oportunidades de aprendizaje.' },
      { title: 'Ayuntamientos', description: 'Apoyo a objetivos comunitarios locales.' },
      { title: 'Organizaciones benéficas', description: 'Financiación de programas comunitarios críticos.' },
      { title: 'Gobierno', description: 'Cumplimiento de objetivos de energía renovable.' },
      { title: 'Comunidades', description: 'Medio ambiente más limpio y empleos locales.' }
    ],
    footerDescription: 'Proporcionando energía a escuelas y comunidades australianas a través de la energía solar comunitaria.',
    quickLinksTitle: 'Enlaces rápidos',
    contactsTitle: 'Contactos',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: 'Perth, Australia Occidental',
    copyright: 'Todos los derechos reservados.',
    privacy: 'Política de privacidad',
    terms: 'Términos de servicio'
    ,
    requiredName: 'Se requiere el nombre completo.',
    requiredOrganization: 'Se requiere el nombre de la organización.',
    requiredPosition: 'Se requiere el puesto.',
    requiredEmail: 'Se requiere la dirección de correo electrónico.',
    invalidEmail: 'Por favor ingrese una dirección de correo electrónico válida.',
    requiredPhone: 'Se requiere número de teléfono.',
    invalidPhone: 'Por favor ingrese un número de teléfono válido (8-15 dígitos).',
    submitting: 'Enviando...'
  },
  zh: {
    logo: 'Kedalup Energy',
    home: '首页',
    about: '关于',
    services: '服务',
    contact: '联系',
    bookPickup: '预订取件',
    languageLabel: '语言',
    heroTitle: '为学校供能。\n赋能社区。',
    heroSubtitle: '通过与原住民社区、学校和慈善机构的可再生能源合作，创造可持续的未来。',
    seeHowItWorks: '了解如何运作',
    getInvolved: '参与其中',
    contactHeading: '准备好改变世界了吗？',
    fullNameLabel: '全名',
    emailLabel: '电子邮件地址',
    phoneLabel: '电话号码',
    organizationLabel: '机构',
    positionLabel: '职位',
    namePlaceholder: '输入您的全名',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: '例如： (08) 9321 0000',
    organizationPlaceholder: '输入机构或学校名称',
    positionPlaceholder: '输入您的职位',
    submitButton: '发送',
    successTitle: '查询提交成功！',
    successMessage: '感谢您联系Kedalup Energy。我们的团队将很快与您联系。',
    sendAnother: '发送另一条消息'
    ,
    challengeHeading: '挑战',
    challengeText: '学校和社区面临日益增长的能源成本和环境挑战。传统的融资模式限制了他们投资可持续解决方案的能力。',
    challengeImageAlt: '屋顶太阳能板阵列反射日落',
    modelTitle: 'Kedalup 模式',
    freeInstallation: '免费安装',
    freeInstallationDesc: '我们在学校免费安装太阳能和电动车站',
    discountedEnergy: '优惠能源',
    discountedEnergyDesc: '通过购电协议提供折扣费率',
    fullMaintenance: '全面维护',
    fullMaintenanceDesc: '包含持续的系统维护和支持',
    profitSharing: '利润分成',
    profitSharingDesc: '50%的利润再投资于学校和慈善机构',
    beneficiariesHeading: '受益者',
    beneficiaries: [
      { title: '学校', description: '降低能源账单和学习机会。' },
      { title: '市政', description: '支持本地社区目标。' },
      { title: '慈善机构', description: '为关键社区项目提供资金。' },
      { title: '政府', description: '实现可再生能源目标。' },
      { title: '社区', description: '更清洁的环境和本地就业。' }
    ],
    footerDescription: '通过社区太阳能为澳大利亚学校和社区提供动力。',
    quickLinksTitle: '快速链接',
    contactsTitle: '联系方式',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: '珀斯，西澳大利亚',
    copyright: '版权所有。',
    privacy: '隐私政策',
    terms: '服务条款'
    ,
    requiredName: '需要输入全名。',
    requiredOrganization: '需要输入机构名称。',
    requiredPosition: '需要输入职位。',
    requiredEmail: '需要输入电子邮件地址。',
    invalidEmail: '请输入有效的电子邮件地址。',
    requiredPhone: '需要输入电话号码。',
    invalidPhone: '请输入有效的电话号码（8-15 位）。',
    submitting: '正在提交...'
  },
  ko: {
    logo: 'Kedalup Energy',
    home: '홈',
    about: '소개',
    services: '서비스',
    contact: '문의하기',
    bookPickup: '픽업 예약',
    languageLabel: '언어',
    heroTitle: '학교에 에너지를 제공합니다.\n커뮤니티에 힘을 실어줍니다.',
    heroSubtitle: '원주민 커뮤니티, 학교 및 자선 단체와 함께 재생 에너지 파트너십을 통해 지속 가능한 미래를 만듭니다.',
    seeHowItWorks: '작동 방식 보기',
    getInvolved: '참여하기',
    contactHeading: '변화를 만들 준비가 되었나요?',
    fullNameLabel: '성명',
    emailLabel: '이메일 주소',
    phoneLabel: '전화번호',
    organizationLabel: '기관',
    positionLabel: '직책',
    namePlaceholder: '성명을 입력하세요',
    emailPlaceholder: 'you@example.com',
    phonePlaceholder: '예: (08) 9321 0000',
    organizationPlaceholder: '기관 또는 학교 이름을 입력하세요',
    positionPlaceholder: '직책을 입력하세요',
    submitButton: '보내기',
    successTitle: '문의가 성공적으로 전송되었습니다!',
    successMessage: 'Kedalup Energy에 문의해 주셔서 감사합니다. 곧 팀에서 연락드리겠습니다.',
    sendAnother: '다른 메시지 보내기'
    ,
    challengeHeading: '과제',
    challengeText: '학교와 지역사회는 증가하는 에너지 비용과 환경 문제에 직면해 있습니다. 전통적인 자금 조달 모델은 지속 가능한 솔루션에 투자할 수 있는 능력을 제한합니다.',
    challengeImageAlt: '일몰을 반사하는 지붕 태양광 패널 배열',
    modelTitle: 'Kedalup 모델',
    freeInstallation: '무료 설치',
    freeInstallationDesc: '학교에 태양광 및 EV 스테이션을 무상으로 설치합니다',
    discountedEnergy: '할인 에너지',
    discountedEnergyDesc: '전력 구매 계약을 통한 할인 요금 제공',
    fullMaintenance: '전체 유지보수',
    fullMaintenanceDesc: '지속적인 시스템 유지보수 및 지원 포함',
    profitSharing: '수익 공유',
    profitSharingDesc: '이익의 50%를 학교 및 자선단체에 재투자',
    beneficiariesHeading: '수혜자',
    beneficiaries: [
      { title: '학교', description: '감소된 에너지 청구서 및 학습 기회.' },
      { title: '지방 정부', description: '지역 사회 목표 지원.' },
      { title: '자선단체', description: '중요한 지역 사회 프로그램 자금 지원.' },
      { title: '정부', description: '재생 에너지 목표 달성.' },
      { title: '지역사회', description: '더 깨끗한 환경과 지역 일자리.' }
    ],
    footerDescription: '커뮤니티 태양광을 통해 호주 학교 및 지역 사회에 전력을 공급합니다.',
    quickLinksTitle: '빠른 링크',
    contactsTitle: '연락처',
    phone: '(08) 9321 0000',
    email: 'info@kedalupenergy.com.au',
    address: '퍼스, 웨스턴오스트레일리아',
    copyright: '판권 소유.',
    privacy: '개인정보 처리방침',
    terms: '서비스 약관'
    ,
    requiredName: '전체 이름은 필수입니다.',
    requiredOrganization: '조직 이름은 필수입니다.',
    requiredPosition: '직함은 필수입니다.',
    requiredEmail: '이메일 주소는 필수입니다.',
    invalidEmail: '유효한 이메일 주소를 입력하세요.',
    requiredPhone: '전화번호는 필수입니다.',
    invalidPhone: '유효한 전화번호를 입력하세요 (8-15자리).',
    submitting: '전송 중...'
  }
}

export default function App() {
  const [language, setLanguage] = useState('en')
  const t = translations[language]

  return (
    <>
      <Navbar t={t} language={language} setLanguage={setLanguage} />
      <main>
        <Hero t={t} />
        <ChallengeModel t={t} />
        <Beneficiaries t={t} />
        <ContactForm t={t} />
      </main>
      <Footer t={t} />
    </>
  )
}
